#!/usr/bin/env ruby

$script_path = File.dirname(__FILE__)

unless ARGV.any?
  $stderr.puts "usage #{$0} <environment-names>"
  exit 1
end

def run_environment(name)
  cmd = [
    File.join($script_path, "run-scenarios"),
    File.join($script_path, "environments", name + ".yml"),
    "--",
    Dir[File.join($script_path, "scenarios", "*.yml")],
    Dir[File.join($script_path, "scenarios", name, "*.yml")]
  ].flatten

  $stderr.puts("$ #{cmd.join(" ")}")
  system(*cmd)
end

ARGV.each do |environment_name|
  run_environment(environment_name)
end
