.k6-base:
  image: ruby:2.6-alpine
  before_script:
    - apk add --no-cache gcc g++ make libc6-compat libc-dev curl
    - gem install bundler && bundle config without dev && bundle install

.report-k6-slack-base:
  stage: report
  extends: .k6-base
  only:
    refs:
      - schedules
  except:
    variables:
      - $CI_SLACK_REPORT != "true"
      - $CI_SLACK_CHANNEL == null
  artifacts:
    when: always
    paths:
      - k6/results/
    expire_in: 14d

.report-k6-wiki-base:
  stage: report
  extends: .k6-base
  when: always
  only:
    refs:
      - schedules
  except:
    variables:
      - $CI_WIKI_REPORT != "true"
  artifacts:
    when: always
    paths:
      - k6/results/
    expire_in: 14d
